---

- name: Installing PostgreSQL YUM repository
  package:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Installing PostgreSQL 11 package
  yum:
    name:
      - postgresql11-server
    state: present
